# Generated by Django 3.1.7 on 2021-05-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210519_0211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='Contact',
        ),
    ]
